#!/bin/sh
# Arg: 1
# nativesdk-shadow - postinst
	if [ "x$D" != "x" ]; then
	  rootarg="--root $D"
	else
	  rootarg=""
	fi

	pwconv $rootarg || exit 1
	grpconv $rootarg || exit 1
	update-alternatives --install /home/zzdc/Workdir1/haobo/imx/tools/meta/sysroots/x86_64-pokysdk-linux/usr/bin/passwd passwd /home/zzdc/Workdir1/haobo/imx/tools/meta/sysroots/x86_64-pokysdk-linux/usr/bin/passwd.shadow 200
	update-alternatives --install /home/zzdc/Workdir1/haobo/imx/tools/meta/sysroots/x86_64-pokysdk-linux/usr/bin/chfn chfn /home/zzdc/Workdir1/haobo/imx/tools/meta/sysroots/x86_64-pokysdk-linux/usr/bin/chfn.shadow 200
	update-alternatives --install /home/zzdc/Workdir1/haobo/imx/tools/meta/sysroots/x86_64-pokysdk-linux/usr/bin/chsh chsh /home/zzdc/Workdir1/haobo/imx/tools/meta/sysroots/x86_64-pokysdk-linux/usr/bin/chsh.shadow 200
	update-alternatives --install /home/zzdc/Workdir1/haobo/imx/tools/meta/sysroots/x86_64-pokysdk-linux/usr/bin/chpasswd chpasswd /home/zzdc/Workdir1/haobo/imx/tools/meta/sysroots/x86_64-pokysdk-linux/usr/bin/chpasswd.shadow 200
	update-alternatives --install /home/zzdc/Workdir1/haobo/imx/tools/meta/sysroots/x86_64-pokysdk-linux/sbin/vipw vipw /home/zzdc/Workdir1/haobo/imx/tools/meta/sysroots/x86_64-pokysdk-linux/sbin/vipw.shadow 200
	update-alternatives --install /home/zzdc/Workdir1/haobo/imx/tools/meta/sysroots/x86_64-pokysdk-linux/sbin/vigr vigr /home/zzdc/Workdir1/haobo/imx/tools/meta/sysroots/x86_64-pokysdk-linux/sbin/vigr.shadow 200